name = "pic-collect-upload"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# R2 存储桶绑定
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "pic-collect"

# 环境变量（公开的）
[vars]
R2_PUBLIC_URL = "https://pub-503f8ebc7e1d4c8eacc08af4f823286d.r2.dev"

# 允许的源（CORS）
[env.production]
name = "pic-collect-upload"
